import { SupplierOrder, ErpItem } from './types';

export const supplierOrders: SupplierOrder[] = [
  {
    id: 'so-001',
    supplierOrderNumber: 'PO-CH-2026-0184',
    supplier: 'Shenzhen ABC Electronics',
    status: 'в_производстве',
    createdAt: '2026-03-10',
    currentStage: 'Производство',
    productionPlan: '2026-08-30',
    deadline: '2026-09-15',
    relatedErpIds: ['erp-001', 'erp-002', 'erp-003'],
  },
  {
    id: 'so-002',
    supplierOrderNumber: 'PO-CH-2026-0192',
    supplier: 'Guangzhou Precision Parts Co.',
    status: 'производство_просрочено',
    createdAt: '2026-02-20',
    currentStage: 'Производство (просрочено)',
    productionPlan: '2026-07-15',
    deadline: '2026-08-20',
    relatedErpIds: ['erp-004', 'erp-005'],
  },
  {
    id: 'so-003',
    supplierOrderNumber: 'PO-CH-2026-0201',
    supplier: 'Shanghai Tech Components Ltd.',
    status: 'ожидаем_клиента',
    createdAt: '2026-04-05',
    currentStage: 'Ожидание ответа клиента',
    productionPlan: '2026-09-10',
    deadline: '2026-10-01',
    relatedErpIds: ['erp-006'],
  },
  {
    id: 'so-004',
    supplierOrderNumber: 'PO-CH-2026-0208',
    supplier: 'Dongguan Metal Works',
    status: 'согласование',
    createdAt: '2026-05-12',
    currentStage: 'Согласование рабочего файла',
    productionPlan: '2026-10-01',
    deadline: '2026-10-30',
    relatedErpIds: ['erp-007', 'erp-008'],
  },
  {
    id: 'so-005',
    supplierOrderNumber: 'PO-CH-2026-0211',
    supplier: 'Wuxi Semiconductor Co.',
    status: 'готово',
    createdAt: '2026-01-15',
    currentStage: 'Готово к отгрузке',
    productionPlan: '2026-06-30',
    deadline: '2026-07-25',
    relatedErpIds: ['erp-009'],
  },
  {
    id: 'so-006',
    supplierOrderNumber: 'PO-CH-2026-0214',
    supplier: 'Shenzhen ABC Electronics',
    status: 'в_доставке',
    createdAt: '2026-03-25',
    currentStage: 'В доставке',
    productionPlan: '2026-07-20',
    deadline: '2026-08-15',
    relatedErpIds: ['erp-010', 'erp-011'],
  },
  {
    id: 'so-007',
    supplierOrderNumber: 'PO-CH-2026-0220',
    supplier: 'Hangzhou Cable Systems',
    status: 'доставлено',
    createdAt: '2026-02-01',
    currentStage: 'Доставлено на склад',
    productionPlan: '2026-05-30',
    deadline: '2026-06-20',
    relatedErpIds: ['erp-012'],
  },
  {
    id: 'so-008',
    supplierOrderNumber: 'PO-CH-2026-0225',
    supplier: 'Ningbo Fasteners Corp.',
    status: 'требует_данных',
    createdAt: '2026-06-01',
    currentStage: 'Требует заполнения данных',
    productionPlan: '2026-11-01',
    deadline: '2026-11-30',
    relatedErpIds: ['erp-013', 'erp-014'],
  },
];

export const erpItems: ErpItem[] = [
  /* === PO-CH-2026-0184 — Shenzhen ABC Electronics (3 items, в производстве) === */
  {
    id: 'erp-001',
    erpCode: 'ERP-104583',
    supplierOrderId: 'so-001',
    nomenclature: 'PCB Control Board Rev.C',
    status: 'в_производстве',
    currentStage: 'Производство',
    comment: 'Плата управления, ревизия C',
    agreement: {
      fileAgreementDeadline: '2026-03-25',
      factoryQuestionsDate: '2026-03-20',
      clientAnswersDate: '2026-03-28',
      daysWaitingClient: 3,
    },
    production: {
      invoiceDeadline: '2026-04-01',
      orderStartDate: '2026-04-05',
      productionStartDate: '2026-04-15',
      productionEndGoldPlan: '2026-08-15',
      productionEndPlan: '2026-08-30',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-09-05',
      deliveryDate: '2026-09-20',
      deliveryDays: 15,
      deliveryMethodDeadline: '2026-09-20',
    },
    deadlines: {
      deadline: '2026-09-15',
      deviation: 0,
      goldDeadline: '2026-09-01',
      goldDeviation: 0,
    },
    problems: {},
    sources: {
      'agreement.fileAgreementDeadline': { type: 'email', label: 'Email', details: 'Письмо от поставщика от 15.03', date: '2026-03-15', emailSubject: 'Production schedule PO-CH-2026-0184', emailFrom: 'supplier@abcelectronics.cn', foundText: 'File agreement deadline March 25' },
      'production.productionStartDate': { type: 'erp', label: 'ERP', details: 'Заказ на производство PR-2026-0410', entityName: 'Производственный заказ', recordId: 'PR-2026-0410', updatedAt: '2026-04-10' },
      'production.productionEndPlan': { type: 'email', label: 'Email', details: 'Письмо от поставщика от 10.04', date: '2026-04-10', emailSubject: 'Updated production timeline', emailFrom: 'supplier@abcelectronics.cn', foundText: 'Production will be completed by August 30' },
    },
    missingFields: ['production.productionEndFact', 'logistics.shipmentDate'],
    conflicts: [],
    trustLevel: 'confirmed',
  },
  {
    id: 'erp-002',
    erpCode: 'ERP-104584',
    supplierOrderId: 'so-001',
    nomenclature: 'Cable Assembly',
    status: 'в_производстве',
    currentStage: 'Производство',
    agreement: {
      fileAgreementDeadline: '2026-03-25',
      factoryQuestionsDate: '2026-03-20',
      clientAnswersDate: '2026-03-28',
      daysWaitingClient: 3,
    },
    production: {
      invoiceDeadline: '2026-04-01',
      orderStartDate: '2026-04-05',
      productionStartDate: '2026-04-18',
      productionEndGoldPlan: '2026-08-20',
      productionEndPlan: '2026-09-05',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-09-10',
      deliveryDate: '2026-09-25',
      deliveryDays: 15,
      deliveryMethodDeadline: '2026-09-25',
    },
    deadlines: {
      deadline: '2026-09-15',
      deviation: 0,
      goldDeadline: '2026-09-05',
      goldDeviation: 0,
    },
    problems: {},
    sources: {
      'production.productionStartDate': { type: 'erp', label: 'ERP', details: 'Заказ на производство PR-2026-0415', entityName: 'Производственный заказ', recordId: 'PR-2026-0415', updatedAt: '2026-04-12' },
    },
    missingFields: ['production.productionEndFact', 'logistics.shipmentDate'],
    conflicts: [],
    trustLevel: 'confirmed',
  },
  {
    id: 'erp-003',
    erpCode: 'ERP-104591',
    supplierOrderId: 'so-001',
    nomenclature: 'Power Module',
    status: 'в_производстве',
    currentStage: 'Производство',
    agreement: {
      fileAgreementDeadline: '2026-03-25',
      factoryQuestionsDate: '2026-03-20',
      clientAnswersDate: '2026-03-28',
      daysWaitingClient: 3,
    },
    production: {
      invoiceDeadline: '2026-04-01',
      orderStartDate: '2026-04-05',
      productionStartDate: '2026-04-12',
      productionEndGoldPlan: '2026-08-10',
      productionEndPlan: '2026-08-25',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-09-01',
      deliveryDate: '2026-09-18',
      deliveryDays: 17,
      deliveryMethodDeadline: '2026-09-18',
    },
    deadlines: {
      deadline: '2026-09-15',
      deviation: 0,
      goldDeadline: '2026-08-28',
      goldDeviation: 0,
    },
    problems: {},
    sources: {},
    missingFields: ['production.productionEndFact', 'logistics.shipmentDate'],
    conflicts: [],
    trustLevel: 'confirmed',
  },

  /* === PO-CH-2026-0192 — Guangzhou Precision Parts (2 items, просрочка) === */
  {
    id: 'erp-004',
    erpCode: 'ERP-104612',
    supplierOrderId: 'so-002',
    nomenclature: 'Precision Shaft Assembly',
    status: 'производство_просрочено',
    currentStage: 'Производство просрочено',
    agreement: {
      fileAgreementDeadline: '2026-03-05',
      factoryQuestionsDate: '2026-03-01',
      clientAnswersDate: '2026-03-07',
      daysWaitingClient: 2,
    },
    production: {
      invoiceDeadline: '2026-03-15',
      orderStartDate: '2026-03-18',
      productionStartDate: '2026-03-25',
      productionEndGoldPlan: '2026-06-30',
      productionEndPlan: '2026-07-15',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 21,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-07-25',
      deliveryDate: '2026-08-10',
      deliveryDays: 16,
      deliveryMethodDeadline: '2026-08-10',
    },
    deadlines: {
      deadline: '2026-08-20',
      deviation: 21,
      goldDeadline: '2026-07-25',
      goldDeviation: 21,
    },
    problems: {
      reason: 'Задержка поставки сырья поставщиком',
      blocker: 'Ожидание поступления алюминиевого сплава',
      responsible: 'Снабженец Иванов',
      comment: 'Поставщик сообщил о задержке сырья на 3 недели',
    },
    sources: {
      'production.supplierDelay': { type: 'email', label: 'Email', details: 'Письмо от поставщика от 20.06', date: '2026-06-20', emailSubject: 'Delay notification PO-CH-2026-0192', emailFrom: 'supplier@gzprecision.cn', foundText: 'Raw material delay of approximately 3 weeks' },
    },
    missingFields: ['production.productionEndFact'],
    conflicts: [],
    trustLevel: 'confirmed',
  },
  {
    id: 'erp-005',
    erpCode: 'ERP-104613',
    supplierOrderId: 'so-002',
    nomenclature: 'Bearing Housing Unit',
    status: 'производство_просрочено',
    currentStage: 'Производство просрочено',
    agreement: {
      fileAgreementDeadline: '2026-03-05',
      factoryQuestionsDate: '2026-03-01',
      clientAnswersDate: '2026-03-07',
      daysWaitingClient: 2,
    },
    production: {
      invoiceDeadline: '2026-03-15',
      orderStartDate: '2026-03-18',
      productionStartDate: '2026-03-28',
      productionEndGoldPlan: '2026-07-05',
      productionEndPlan: '2026-07-20',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 21,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-07-30',
      deliveryDate: '2026-08-15',
      deliveryDays: 16,
      deliveryMethodDeadline: '2026-08-15',
    },
    deadlines: {
      deadline: '2026-08-20',
      deviation: 21,
      goldDeadline: '2026-07-25',
      goldDeviation: 21,
    },
    problems: {
      reason: 'Задержка поставки сырья поставщиком',
      blocker: 'Ожидание поступления алюминиевого сплава',
      responsible: 'Снабженец Иванов',
    },
    sources: {},
    missingFields: ['production.productionEndFact'],
    conflicts: [],
    trustLevel: 'confirmed',
  },

  /* === PO-CH-2026-0201 — Shanghai Tech Components (1 item, ожидаем клиента) === */
  {
    id: 'erp-006',
    erpCode: 'ERP-104701',
    supplierOrderId: 'so-003',
    nomenclature: 'Temperature Sensor Module',
    status: 'ожидаем_клиента',
    currentStage: 'Ожидание ответа клиента',
    agreement: {
      fileAgreementDeadline: '2026-05-01',
      factoryQuestionsDate: '2026-04-25',
      clientAnswersDate: undefined,
      daysWaitingClient: 14,
    },
    production: {
      invoiceDeadline: '2026-05-15',
      orderStartDate: undefined,
      productionStartDate: undefined,
      productionEndGoldPlan: '2026-08-20',
      productionEndPlan: '2026-09-10',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-09-15',
      deliveryDate: '2026-10-01',
      deliveryDays: 16,
      deliveryMethodDeadline: '2026-10-01',
    },
    deadlines: {
      deadline: '2026-10-01',
      deviation: 0,
      goldDeadline: '2026-09-15',
      goldDeviation: 0,
    },
    problems: {
      reason: 'Ожидание ответа клиента на вопросы завода',
      blocker: 'Нет ответа на запрос от 25.04',
      responsible: 'Логист Петрова',
      comment: 'Отправили запрос заводу, ждём ответа 14 дней',
    },
    sources: {
      'agreement.factoryQuestionsDate': { type: 'email', label: 'Email', details: 'Письмо от завода от 25.04', date: '2026-04-25', emailSubject: 'Technical questions PO-CH-2026-0201', emailFrom: 'factory@shanghaitech.cn', foundText: 'Please clarify specifications for temperature range' },
    },
    missingFields: ['agreement.clientAnswersDate', 'production.orderStartDate', 'production.productionStartDate'],
    conflicts: [],
    trustLevel: 'needs_review',
  },

  /* === PO-CH-2026-0208 — Dongguan Metal Works (2 items, согласование) === */
  {
    id: 'erp-007',
    erpCode: 'ERP-104723',
    supplierOrderId: 'so-004',
    nomenclature: 'Metal Enclosure Frame',
    status: 'согласование',
    currentStage: 'Согласование рабочего файла',
    agreement: {
      fileAgreementDeadline: '2026-06-15',
      factoryQuestionsDate: '2026-06-01',
      clientAnswersDate: undefined,
      daysWaitingClient: 7,
    },
    production: {
      invoiceDeadline: '2026-06-20',
      orderStartDate: undefined,
      productionStartDate: undefined,
      productionEndGoldPlan: '2026-09-15',
      productionEndPlan: '2026-10-01',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-10-05',
      deliveryDate: '2026-10-25',
      deliveryDays: 20,
      deliveryMethodDeadline: '2026-10-25',
    },
    deadlines: {
      deadline: '2026-10-30',
      deviation: 0,
      goldDeadline: '2026-10-15',
      goldDeviation: 0,
    },
    problems: {
      reason: 'Рабочий файл не согласован',
      blocker: 'Ожидание утверждения чертежей',
      responsible: 'Снабженец Иванов',
    },
    sources: {},
    missingFields: ['agreement.clientAnswersDate', 'production.orderStartDate', 'production.productionStartDate'],
    conflicts: [],
    trustLevel: 'needs_review',
  },
  {
    id: 'erp-008',
    erpCode: 'ERP-104724',
    supplierOrderId: 'so-004',
    nomenclature: 'Mounting Bracket Set',
    status: 'согласование',
    currentStage: 'Согласование рабочего файла',
    agreement: {
      fileAgreementDeadline: '2026-06-15',
      factoryQuestionsDate: '2026-06-01',
      clientAnswersDate: undefined,
      daysWaitingClient: 7,
    },
    production: {
      invoiceDeadline: '2026-06-20',
      orderStartDate: undefined,
      productionStartDate: undefined,
      productionEndGoldPlan: '2026-09-20',
      productionEndPlan: '2026-10-05',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-10-10',
      deliveryDate: '2026-10-30',
      deliveryDays: 20,
      deliveryMethodDeadline: '2026-10-30',
    },
    deadlines: {
      deadline: '2026-10-30',
      deviation: 0,
      goldDeadline: '2026-10-20',
      goldDeviation: 0,
    },
    problems: {
      reason: 'Рабочий файл не согласован',
      blocker: 'Ожидание утверждения чертежей',
      responsible: 'Снабженец Иванов',
    },
    sources: {},
    missingFields: ['agreement.clientAnswersDate', 'production.orderStartDate', 'production.productionStartDate'],
    conflicts: [],
    trustLevel: 'needs_review',
  },

  /* === PO-CH-2026-0211 — Wuxi Semiconductor (1 item, готово) === */
  {
    id: 'erp-009',
    erpCode: 'ERP-104801',
    supplierOrderId: 'so-005',
    nomenclature: 'Semiconductor Test Board',
    status: 'готово',
    currentStage: 'Готово к отгрузке',
    agreement: {
      fileAgreementDeadline: '2026-02-01',
      factoryQuestionsDate: '2026-01-25',
      clientAnswersDate: '2026-01-30',
      daysWaitingClient: 2,
    },
    production: {
      invoiceDeadline: '2026-02-10',
      orderStartDate: '2026-02-12',
      productionStartDate: '2026-02-20',
      productionEndGoldPlan: '2026-06-15',
      productionEndPlan: '2026-06-30',
      productionEndFact: '2026-06-25',
      factProductionDays: 125,
      supplierDelay: 0,
      readyForShipment: true,
    },
    logistics: {
      shipmentDeadline: '2026-07-05',
      deliveryNumber: 'DEL-2026-0789',
      shipmentDate: '2026-07-10',
      deliveryDate: '2026-07-22',
      deliveryDays: 12,
      deliveryMethodDeadline: '2026-07-25',
    },
    deadlines: {
      deadline: '2026-07-25',
      deviation: -3,
      goldDeadline: '2026-07-10',
      goldDeviation: 12,
    },
    problems: {},
    sources: {
      'production.productionEndFact': { type: 'email', label: 'Email', details: 'Письмо от поставщика от 25.06', date: '2026-06-25', emailSubject: 'Production completed PO-CH-2026-0211', emailFrom: 'factory@wuxisemi.cn', foundText: 'Production completed on June 25' },
      'logistics.shipmentDate': { type: 'erp', label: 'ERP', details: 'Отгрузка DEL-2026-0789', entityName: 'Отгрузка', recordId: 'DEL-2026-0789', updatedAt: '2026-07-10' },
    },
    missingFields: [],
    conflicts: [],
    trustLevel: 'confirmed',
  },

  /* === PO-CH-2026-0214 — Shenzhen ABC Electronics (2 items, в доставке) === */
  {
    id: 'erp-010',
    erpCode: 'ERP-104850',
    supplierOrderId: 'so-006',
    nomenclature: 'Power Supply Unit 12V',
    status: 'в_доставке',
    currentStage: 'В доставке',
    agreement: {
      fileAgreementDeadline: '2026-04-10',
      factoryQuestionsDate: '2026-04-05',
      clientAnswersDate: '2026-04-12',
      daysWaitingClient: 4,
    },
    production: {
      invoiceDeadline: '2026-04-20',
      orderStartDate: '2026-04-22',
      productionStartDate: '2026-05-01',
      productionEndGoldPlan: '2026-07-10',
      productionEndPlan: '2026-07-20',
      productionEndFact: '2026-07-18',
      factProductionDays: 78,
      supplierDelay: 0,
      readyForShipment: true,
    },
    logistics: {
      shipmentDeadline: '2026-07-25',
      deliveryNumber: 'DEL-2026-0812',
      shipmentDate: '2026-07-28',
      deliveryDate: undefined,
      deliveryDays: undefined,
      deliveryMethodDeadline: '2026-08-15',
    },
    deadlines: {
      deadline: '2026-08-15',
      deviation: 0,
      goldDeadline: '2026-08-01',
      goldDeviation: 0,
    },
    problems: {},
    sources: {
      'production.productionEndFact': { type: 'erp', label: 'ERP', details: 'Производственный заказ PR-2026-0515', entityName: 'Производственный заказ', recordId: 'PR-2026-0515', updatedAt: '2026-07-18' },
      'logistics.shipmentDate': { type: 'email', label: 'Email', details: 'Письмо от поставщика от 28.07', date: '2026-07-28', emailSubject: 'Shipment notification PO-CH-2026-0214', emailFrom: 'supplier@abcelectronics.cn', foundText: 'Goods shipped on July 28' },
    },
    missingFields: ['logistics.deliveryDate'],
    conflicts: [],
    trustLevel: 'confirmed',
  },
  {
    id: 'erp-011',
    erpCode: 'ERP-104851',
    supplierOrderId: 'so-006',
    nomenclature: 'Backup Battery Module',
    status: 'в_доставке',
    currentStage: 'В доставке',
    agreement: {
      fileAgreementDeadline: '2026-04-10',
      factoryQuestionsDate: '2026-04-05',
      clientAnswersDate: '2026-04-12',
      daysWaitingClient: 4,
    },
    production: {
      invoiceDeadline: '2026-04-20',
      orderStartDate: '2026-04-22',
      productionStartDate: '2026-05-05',
      productionEndGoldPlan: '2026-07-15',
      productionEndPlan: '2026-07-25',
      productionEndFact: '2026-07-22',
      factProductionDays: 78,
      supplierDelay: 0,
      readyForShipment: true,
    },
    logistics: {
      shipmentDeadline: '2026-07-30',
      deliveryNumber: 'DEL-2026-0812',
      shipmentDate: '2026-07-28',
      deliveryDate: undefined,
      deliveryDays: undefined,
      deliveryMethodDeadline: '2026-08-15',
    },
    deadlines: {
      deadline: '2026-08-15',
      deviation: 0,
      goldDeadline: '2026-08-01',
      goldDeviation: 0,
    },
    problems: {},
    sources: {},
    missingFields: ['logistics.deliveryDate'],
    conflicts: [],
    trustLevel: 'confirmed',
  },

  /* === PO-CH-2026-0220 — Hangzhou Cable Systems (1 item, доставлено) === */
  {
    id: 'erp-012',
    erpCode: 'ERP-104901',
    supplierOrderId: 'so-007',
    nomenclature: 'Industrial Control Cable 50m',
    status: 'доставлено',
    currentStage: 'Доставлено на склад',
    agreement: {
      fileAgreementDeadline: '2026-02-20',
      factoryQuestionsDate: '2026-02-15',
      clientAnswersDate: '2026-02-22',
      daysWaitingClient: 3,
    },
    production: {
      invoiceDeadline: '2026-03-01',
      orderStartDate: '2026-03-05',
      productionStartDate: '2026-03-10',
      productionEndGoldPlan: '2026-05-20',
      productionEndPlan: '2026-05-30',
      productionEndFact: '2026-05-25',
      factProductionDays: 76,
      supplierDelay: 0,
      readyForShipment: true,
    },
    logistics: {
      shipmentDeadline: '2026-06-01',
      deliveryNumber: 'DEL-2026-0654',
      shipmentDate: '2026-06-03',
      deliveryDate: '2026-06-15',
      deliveryDays: 12,
      deliveryMethodDeadline: '2026-06-20',
    },
    deadlines: {
      deadline: '2026-06-20',
      deviation: -5,
      goldDeadline: '2026-06-10',
      goldDeviation: 5,
    },
    problems: {},
    sources: {
      'logistics.deliveryDate': { type: 'erp', label: 'ERP', details: 'Поступление на склад 15.06', entityName: 'Приходная накладная', recordId: 'REC-2026-0341', updatedAt: '2026-06-15' },
    },
    missingFields: [],
    conflicts: [],
    trustLevel: 'confirmed',
  },

  /* === PO-CH-2026-0225 — Ningbo Fasteners (2 items, требует данных) === */
  {
    id: 'erp-013',
    erpCode: 'ERP-104950',
    supplierOrderId: 'so-008',
    nomenclature: 'Hex Bolt M12 Set',
    status: 'требует_данных',
    currentStage: 'Требует заполнения данных',
    agreement: {
      fileAgreementDeadline: undefined,
      factoryQuestionsDate: undefined,
      clientAnswersDate: undefined,
      daysWaitingClient: undefined,
    },
    production: {
      invoiceDeadline: undefined,
      orderStartDate: undefined,
      productionStartDate: undefined,
      productionEndGoldPlan: '2026-10-15',
      productionEndPlan: '2026-11-01',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: undefined,
      deliveryDate: undefined,
      deliveryDays: undefined,
      deliveryMethodDeadline: undefined,
    },
    deadlines: {
      deadline: '2026-11-30',
      deviation: 0,
      goldDeadline: '2026-11-15',
      goldDeviation: 0,
    },
    problems: {
      reason: 'Недостаточно данных для запуска',
      comment: 'Требуется согласование спецификации',
    },
    sources: {},
    missingFields: ['agreement.fileAgreementDeadline', 'agreement.factoryQuestionsDate', 'production.invoiceDeadline', 'production.orderStartDate', 'logistics.shipmentDeadline'],
    conflicts: [],
    trustLevel: 'needs_review',
  },
  {
    id: 'erp-014',
    erpCode: 'ERP-104951',
    supplierOrderId: 'so-008',
    nomenclature: 'Washer M12 Pack 100pcs',
    status: 'требует_данных',
    currentStage: 'Требует заполнения данных',
    agreement: {
      fileAgreementDeadline: undefined,
      factoryQuestionsDate: undefined,
      clientAnswersDate: undefined,
      daysWaitingClient: undefined,
    },
    production: {
      invoiceDeadline: undefined,
      orderStartDate: undefined,
      productionStartDate: undefined,
      productionEndGoldPlan: '2026-10-20',
      productionEndPlan: '2026-11-05',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: undefined,
      deliveryDate: undefined,
      deliveryDays: undefined,
      deliveryMethodDeadline: undefined,
    },
    deadlines: {
      deadline: '2026-11-30',
      deviation: 0,
      goldDeadline: '2026-11-20',
      goldDeviation: 0,
    },
    problems: {
      reason: 'Недостаточно данных для запуска',
    },
    sources: {},
    missingFields: ['agreement.fileAgreementDeadline', 'agreement.factoryQuestionsDate', 'production.invoiceDeadline', 'production.orderStartDate', 'logistics.shipmentDeadline'],
    conflicts: [],
    trustLevel: 'needs_review',
  },

  /* === Unlinked ERP items (no supplier order) === */
  {
    id: 'erp-015',
    erpCode: 'ERP-104702',
    supplierOrderId: null,
    nomenclature: 'Cooling Fan Unit',
    status: 'требует_данных',
    currentStage: 'Не связан с заказом',
    agreement: {},
    production: {},
    logistics: {},
    deadlines: {},
    problems: {
      comment: 'Не удалось определить заказ поставщику',
    },
    sources: {},
    missingFields: ['supplierOrderId'],
    conflicts: [],
    trustLevel: 'needs_review',
  },
  {
    id: 'erp-016',
    erpCode: 'ERP-104703',
    supplierOrderId: null,
    nomenclature: 'Connector Housing Set',
    status: 'требует_данных',
    currentStage: 'Не связан с заказом',
    agreement: {},
    production: {},
    logistics: {},
    deadlines: {},
    problems: {
      comment: 'Не удалось определить заказ поставщику',
    },
    sources: {},
    missingFields: ['supplierOrderId'],
    conflicts: [],
    trustLevel: 'needs_review',
  },

  /* === ERP with data conflict === */
  {
    id: 'erp-017',
    erpCode: 'ERP-104960',
    supplierOrderId: 'so-001',
    nomenclature: 'Control Board Housing',
    status: 'в_производстве',
    currentStage: 'Производство',
    agreement: {
      fileAgreementDeadline: '2026-04-01',
      factoryQuestionsDate: '2026-03-28',
      clientAnswersDate: '2026-04-03',
      daysWaitingClient: 3,
    },
    production: {
      invoiceDeadline: '2026-04-10',
      orderStartDate: '2026-04-12',
      productionStartDate: '2026-04-20',
      productionEndGoldPlan: '2026-08-20',
      productionEndPlan: '2026-09-05',
      productionEndFact: undefined,
      factProductionDays: undefined,
      supplierDelay: 0,
      readyForShipment: false,
    },
    logistics: {
      shipmentDeadline: '2026-09-10',
      deliveryDate: '2026-09-25',
      deliveryDays: 15,
      deliveryMethodDeadline: '2026-09-25',
    },
    deadlines: {
      deadline: '2026-09-15',
      deviation: 0,
      goldDeadline: '2026-09-01',
      goldDeviation: 0,
    },
    problems: {},
    sources: {
      'production.productionEndPlan': { type: 'email', label: 'Email', details: 'Письмо от 05.08 — дата 22.08', date: '2026-08-05', emailSubject: 'Production update PO-CH-2026-0184', emailFrom: 'supplier@abcelectronics.cn', foundText: 'Production end date August 22' },
    },
    missingFields: ['production.productionEndFact'],
    conflicts: [
      {
        field: 'production.productionEndPlan',
        values: [
          { value: '2026-08-22', source: { type: 'email', label: 'Email', details: 'Письмо от 05.08', date: '2026-08-05', emailSubject: 'Production update PO-CH-2026-0184', emailFrom: 'supplier@abcelectronics.cn', foundText: 'Production end date August 22' } },
          { value: '2026-08-25', source: { type: 'email', label: 'Email', details: 'Письмо от 09.08', date: '2026-08-09', emailSubject: 'Revised schedule PO-CH-2026-0184', emailFrom: 'supplier@abcelectronics.cn', foundText: 'Updated production completion August 25' } },
        ],
        selectedValue: '2026-08-25',
      },
    ],
    trustLevel: 'conflict',
  },
];